services:
  - type: web
    name: doctorAppDjangoREST
    runtime: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput"
    startCommand: "gunicorn config.wsgi --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "doctorappdjangorest.onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://doctor-app-django-rest.vercel.app,http://localhost:3000"
      - key: PYTHON_VERSION
        value: "3.12.8"
